name: Matrix Workflow
on:
  push:
    branches:
      - main
jobs:
  continue-on-failure: true 
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operation-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix['operation-system'] }}
    steps:
      - name: Set up Node.js ${{ matrix['node-version'] }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix['node-version'] }}
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with: