name: Resuable Workflow
on: 
  workflow_call
    inputs:
      artifact-name:
        description: 'Name of the artifact to download'
        required: true
        type: string
        default: 'dist-files'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{}{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: displayname
        run: echo "This is a reusable workflow"